
<?php
/* +----------------------------------------------------------------------
 * | 数据接口信息数组（还有部分数据信息在使用中）
 * +----------------------------------------------------------------------
 * | Copyright (c) 2016 http://www.qqty.com All rights reserved.
 * +----------------------------------------------------------------------
 * | Author: Knight <fxwcq@sina.cn> <http://www.Knight.cn>
 * +----------------------------------------------------------------------
 */ 
 return array (
  'bf' =>
  array (
    'name' => 'bf',
    'pName' => 'football',
    'url' => 'data/bf.js',
    'sendUrl' => 'http://live1.nowscore.com/data/bf.js?[T]',
    'savePath' => 'football/bf/',
    'cacheTime' => '300',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '0',
    'explain' => '比分直播数据包JS文件',
    'mimeType' => 'application/x-javascript',
    'returnType' => '2',
    'errorMsg' => 'var A=Array(2);
var B=Array(2);
var C=Array(2);
var matchcount=2;
var sclasscount=0;
var countrycount=0;
var matchdate="00月00日"
A[0]=[0,0,0,0,\'请购买正版\',\'請購買正版\',\'Please buy genuine\',\'未注册版本\',\'未註冊版本\',\'Unregistered version\',\'00:00\',\'2011,0,8,17,27,35\',0,0,0,0,0,0,0,0,0,\'\',\'\',,\'\',0,\'\',\'\',0,0,0,21];
A[1]=[1,1,0,0,\'联系电话\',\'聯繫電話\',\'Contact\',\'13414952822\',\'13414952822\',\'13414952822\',\'00:00\',\'2011,0,8,17,30,35\',0,0,0,0,0,0,0,0,0,\'\',\'\',,\'\',0,\'\',\'\',0,0,0,13];
B[0]=[39,\'凡智网络\',\'凡智網絡\',\'vanchi.net\',\'#FF850B\',1,1,\'\',0,1,0];
B[1]=[35,\'凡智网络\',\'凡智網絡\',\'vanchi.net\',\'#FFBA75\',0,1,\'\',0,1,0];
C[0]=[1,\'凡智网络\',0,0];
C[1]=[2,\'凡智网络\',0,0];
ShowBf();',
    'cTime' => '150',
    'upTime' => 0,
  ),
  'change2' =>
  array (
    'name' => 'change2',
    'pName' => 'football',
    'url' => 'data/change2.xml',
    'sendUrl' => 'http://live1.nowscore.com/data/change2.xml?[T]',
    'savePath' => 'football/change2/',
    'cacheTime' => '0',
    'charset' => 'gbk',
    'isUtf8' => '1',
    'isID' => '0',
    'explain' => '足球现场数据change2.xml文件',
    'mimeType' => 'text/xml',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '0',
    'upTime' => 0,
  ),
  'scorelist' =>
  array (
    'name' => 'scorelist',
    'pName' => 'football',
    'url' => 'data/score.aspx?[URI]',
    'sendUrl' => 'http://live1.nowscore.com/data/score.aspx?date=[Date]',
    'savePath' => 'football/scorelist/',
    'cacheTime' => '3600',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '0',
    'explain' => '完场比分、一周赛程数据查询接口。',
    'mimeType' => 'text/html',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '1800',
    'upTime' => 0,
  ),
  'change' =>
  array (
    'name' => 'change',
    'pName' => 'football',
    'url' => 'data/change.xml',
    'sendUrl' => 'http://live1.nowscore.com/data/change.xml?[T]',
    'savePath' => 'football/change/',
    'cacheTime' => '0',
    'charset' => 'gbk',
    'isUtf8' => '1',
    'isID' => '0',
    'explain' => '足球现场数据change.xml文件
encoding="UTF-8"',
    'mimeType' => 'text/xml',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '0',
    'upTime' => 0,
  ),
  'goal' =>
  array (
    'name' => 'goal',
    'pName' => 'football',
    'url' => 'data/ch_goal[URI].xml',
    'sendUrl' => 'http://live1.nowscore.com/data/ch_goal3.xml?[T]',
    'savePath' => 'football/goal/',
    'cacheTime' => '0',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '1',
    'explain' => '赔率公司开盘xml数据，用于比分二合一页面。data/ch_goal[URI].xml',
    'mimeType' => 'text/xml',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '0',
    'upTime' => 0,
  ),
  'goals' =>
  array (
    'name' => 'goals',
    'pName' => 'football',
    'url' => 'data/goal[URI].xml',
    'sendUrl' => 'http://live1.nowscore.com/data/goal3.xml?t=[T]',
    'savePath' => 'football/goals/',
    'cacheTime' => '600',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '1',
    'explain' => '赛事赔率数据包，data/goal[URI].xml',
    'mimeType' => 'text/xml',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '300',
    'upTime' => 0,
  ),
  'analysis' =>
  array (
    'name' => 'analysis',
    'pName' => 'football',
    'url' => 'analysis/[URI].html',
    'sendUrl' => 'http://live1.nowscore.com/analysis/[CID].html',
    'savePath' => 'football/analysis/',
    'cacheTime' => '3600',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '1',
    'explain' => '比赛分析,数据比较,历史交战数据比较。',
    'mimeType' => '',
    'returnType' => '3',
    'errorMsg' => '',
    'cTime' => '1800',
    'upTime' => 0,
  ),
  'detail_js' =>
  array (
    'name' => 'detail_js',
    'pName' => 'football',
    'url' => 'data/detail.js',
    'sendUrl' => 'http://live1.nowscore.com/data/detail.js?[T]',
    'savePath' => 'football/detail_js/',
    'cacheTime' => '300',
    'charset' => 'gbk',
    'isUtf8' => '1',
    'isID' => '0',
    'explain' => '现场比分数据鼠标指向比分显示浮动层。',
    'mimeType' => 'application/x-javascript',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '150',
    'upTime' => 0,
  ),
  'panlu_js' =>
  array (
    'name' => 'panlu_js',
    'pName' => 'football',
    'url' => 'data/panlu.js',
    'sendUrl' => 'http://live1.nowscore.com/data/panlu.js?[T]',
    'savePath' => 'football/panlu_js/',
    'cacheTime' => '43200',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '0',
    'explain' => '盘路统计JS数据包',
    'mimeType' => 'application/x-javascript',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '21600',
    'upTime' => 0,
  ),
  'OddsDataDiv' =>
  array (
    'name' => 'OddsDataDiv',
    'pName' => 'football',
    'url' => 'http://info5.90bfw.com/datajs/modds.js',
    'sendUrl' => 'http://info5.90bfw.com/datajs/modds.js?[T]',
    'savePath' => 'football/OddsDataDiv/',
    'cacheTime' => '0',
    'charset' => 'gbk',
    'isUtf8' => '1',
    'isID' => '0',
    'explain' => '足球盘口提示层数据接口',
    'mimeType' => 'application/x-javascript',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '0',
    'upTime' => 0,
  ),
  'indexAjaxLeague' =>
  array (
    'name' => 'indexAjaxLeague',
    'pName' => 'football',
    'url' => 'AjaxLeague.aspx?[URI]',
    'sendUrl' => 'http://info.nowscore.com/AjaxLeague.aspx?sclassid=[CID]&sclasstype=[ST]&v=[T]',
    'savePath' => 'football/indexAjaxLeague/',
    'cacheTime' => '86400',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '0',
    'explain' => '首页_调用赛程赛果接口',
    'mimeType' => 'text/plain',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '43200',
    'upTime' => 0,
  ),
  'pk' =>
  array (
    'name' => 'pk',
    'pName' => 'football',
    'url' => 'http://live1.nowscore.com/detail/[URI].html',
    'sendUrl' => 'http://live1.nowscore.com/detail/[CID].html',
    'savePath' => 'football/pk/',
    'cacheTime' => '300',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '1',
    'explain' => '赛事现场信息',
    'mimeType' => 'text/html',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '300',
    'upTime' => 0,
  ),
  'match' =>
  array (
    'name' => 'match',
    'pName' => 'football',
    'url' => 'http://live1.nowscore.com/odds/match.aspx?id=[URI]',
    'sendUrl' => 'http://live1.nowscore.com/odds/match.aspx?id=[CID]',
    'savePath' => 'football/match/',
    'cacheTime' => '3600',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '1',
    'explain' => '赔率三合一数据页',
    'mimeType' => 'text/html',
    'returnType' => '3',
    'errorMsg' => '',
    'cTime' => '300',
    'upTime' => 0,
  ),
  '1x2' =>
  array (
    'name' => '1x2',
    'pName' => 'football',
    'url' => 'http://1x2.nowscore.com/[URI].js',
    'sendUrl' => 'http://1x2.nowscore.com/[CID].js',
    'savePath' => 'football/1x2/',
    'cacheTime' => '3600',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '1',
    'explain' => '百家欧赔数据',
    'mimeType' => 'application/x-javascript',
    'returnType' => '3',
    'errorMsg' => '',
    'cTime' => '300',
    'upTime' => 0,
  ),
  'ch_odds' =>
  array (
    'name' => 'ch_odds',
    'pName' => 'football',
    'url' => 'http://score.nowscore.com/odds/xml/ch_odds.xml',
    'sendUrl' => 'http://score.nowscore.com/odds/xml/ch_odds.xml?[T]',
    'savePath' => 'football/ch_odds/',
    'cacheTime' => 0,
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '0',
    'explain' => '即时赔率数据接口',
    'mimeType' => 'text/xml',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => 0,
    'upTime' => 0,
  ),
  'xmlodds' =>
  array (
    'name' => 'xmlodds',
    'pName' => 'football',
    'url' => 'http://score.nowscore.com/odds/xml/odds.aspx?[URI]',
    'sendUrl' => 'http://score.nowscore.com/odds/xml/odds.aspx?companyID=,9,14,3,4,24,1,19,12,18,7,8,17,23,31,35,22,&t=[T]',
    'savePath' => 'football/xmlodds/',
    'cacheTime' => 0,
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '0',
    'explain' => '赔率数据接口',
    'mimeType' => 'text/plain',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => 0,
    'upTime' => 0,
  ),
  #篮球url
  'todaynbascores' =>
  array (
    'name' => 'todaynbascores',
    'pName' => 'basketball',
    'url' => 'http://live1.nowscore.com/nba/nba.xml',
    'sendUrl' => 'http://live1.nowscore.com/nba/nba.xml?[T]',
    'savePath' => 'basketball/todaynbascores/',
    'cacheTime' => '3600',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '0',
    'explain' => '今日篮球赛事数据接口',
    'mimeType' => 'text/xml',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '1800',
    'upTime' => 0,
  ),
  'nbascore' =>
  array (
    'name' => 'nbascore',
    'pName' => 'basketball',
    'url' => 'http://live1.nowscore.com/NBA/Score.aspx?[URI]',
    'sendUrl' => 'http://live1.nowscore.com/NBA/Score.aspx?date=[Date]&t=[T]',
    'savePath' => 'basketball/nbascore/',
    'cacheTime' => '3600',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '0',
    'explain' => '篮球实时赛事接口',
    'mimeType' => 'text/xml',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '1800',
    'upTime' => 0,
  ),
  'nbachange' =>
  array (
    'name' => 'nbachange',
    'pName' => 'basketball',
    'url' => 'http://live1.nowscore.com/nba/change.xml',
    'sendUrl' => 'http://live1.nowscore.com/nba/change.xml?t=[T]',
    'savePath' => 'basketball/nbachange/',
    'cacheTime' => '0',
    'charset' => 'gb2312',
    'isUtf8' => '1',
    'isID' => '0',
    'explain' => '篮球实时赛果接口',
    'mimeType' => 'text/xml',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '0',
    'upTime' => 0,
  ),
  'nbaodds' =>
  array (
    'name' => 'nbaodds',
    'pName' => 'basketball',
    'url' => 'http://live1.nowscore.com/nba/odds.aspx?[URI]',
    'sendUrl' => 'http://live1.nowscore.com/nba/odds.aspx?date=[Date]&t=[T]',
    'savePath' => 'basketball/nbaodds/',
    'cacheTime' => '120',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '0',
    'explain' => '篮球赛事赔率接口',
    'mimeType' => 'text/xml',
    'returnType' => '2',
    'errorMsg' => '',
    'cTime' => '60',
    'upTime' => 0,
  ),
  'nbaanalysis' =>
  array (
    'name' => 'nbaanalysis',
    'pName' => 'basketball',
    'url' => 'http://live1.nowscore.com/nbaAnalysis/[URI].html',
    'sendUrl' => 'http://live1.nowscore.com/nbaAnalysis/[CID].html',
    'savePath' => 'basketball/nbaanalysis/',
    'cacheTime' => '43200',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '1',
    'explain' => '对战分析_篮球',
    'mimeType' => 'text/html',
    'returnType' => '3',
    'errorMsg' => '',
    'cTime' => 43200,
    'upTime' => 0,
  ),
  'nbaoddscomp' =>
  array (
    'name' => 'nbaoddscomp',
    'pName' => 'basketball',
    'url' => 'http://live1.nowscore.com/NBA/OddsComp.aspx?[URI]',
    'sendUrl' => 'http://live1.nowscore.com/NBA/OddsComp.aspx?id=[CID]',
    'savePath' => 'basketball/nbaoddscomp/',
    'cacheTime' => '43200',
    'charset' => '',
    'isUtf8' => '0',
    'isID' => '1',
    'explain' => '篮球_赔率三合一',
    'mimeType' => 'text/html',
    'returnType' => '3',
    'errorMsg' => '',
    'cTime' => 43200,
    'upTime' => 0,
  ),
);
?>