<?php
// 专家推荐封面生成配置
return array(
    'cover'=>[
        'temp1'=>[
            'temp_path' => 'Public/Home/images/expert/templet/temp1.png',
            'home_logo_x' => 44,
            'home_logo_y' => 157,
            'away_logo_x' => 368,
            'away_logo_y' => 157,
            'font_r' => 255,
            'font_g' => 255,
            'font_b' => 255,
            'font_size' => 36,
            'home_font_x' => 18,
            'home_font_y' => 118,
            'away_font_x' => 562,
            'away_font_y' => 118,
        ],
        'temp2'=>[
            'temp_path' => 'Public/Home/images/expert/templet/temp2.png',
            'home_logo_x' => 66,
            'home_logo_y' => 50,
            'away_logo_x' => 354,
            'away_logo_y' => 137,
            'font_r' => 255,
            'font_g' => 255,
            'font_b' => 255,
            'font_size' => 36,
            'home_font_x' => 150,
            'home_font_y' => 320,
            'away_font_x' => 440,
            'away_font_y' => 400,
        ],
        'temp3'=>[
            'temp_path' => 'Public/Home/images/expert/templet/temp3.png',
            'home_logo_x' => 25,
            'home_logo_y' => 45,
            'away_logo_x' => 385,
            'away_logo_y' => 189,
            'font_r' => 255,
            'font_g' => 255,
            'font_b' => 255,
            'font_size' => 36,
            'home_font_x' => 220,
            'home_font_y' => 148,
            'away_font_x' => 365,
            'away_font_y' => 315,
        ],
        'temp4'=>[
            'temp_path' => 'Public/Home/images/expert/templet/temp4.png',
            'home_logo_x' => 26,
            'home_logo_y' => 14,
            'away_logo_x' => 25,
            'away_logo_y' => 221,
            'font_r' => 255,
            'font_g' => 255,
            'font_b' => 255,
            'font_size' => 36,
            'home_font_x' => 230,
            'home_font_y' => 124,
            'away_font_x' => 230,
            'away_font_y' => 335,
        ],
        'temp5'=>[
            'temp_path' => 'Public/Home/images/expert/templet/temp5.png',
            'home_logo_x' => 40,
            'home_logo_y' => 44,
            'away_logo_x' => 370,
            'away_logo_y' => 190,
            'font_r' => 255,
            'font_g' => 255,
            'font_b' => 255,
            'font_size' => 36,
            'home_font_x' => 250,
            'home_font_y' => 90,
            'away_font_x' => 40,
            'away_font_y' => 360,
        ],
        'temp7'=>[
            'temp_path' => 'Public/Home/images/expert/templet/temp7.png',
            'temp_path_b' => 'Public/Home/images/expert/templet/temp9.png',
            'home_logo_x' => 37,
            'home_logo_y' => 83,
            'away_logo_x' => 374,
            'away_logo_y' => 83,
        ]
    ]
);
?>