<?php
/**

本配置在各版本的Api接口模块通用，修改时请注意兼容

 */

// 外挂足球赔率公司ID配置文件
return array(
    'DB_COMPANY_INFO' => array (
        1  => '澳门',
        3  => 'SB',
        4  => '立博',
        8  => 'Bet365',
        12 => '易胜博',
        17 => '明陞',
        23 => '金宝博',
        24 => '沙巴',
        31 => '利记',
      ),
    'DB_COMPANY_ODDS' =>array (
        1  => '澳门',
        4  => '立博',
        3  => 'SB',
        24 => '沙巴',   //12Bet
        8  => 'Bet365',
        17 => '明陞',
        12 => '易胜博',
        31 => '利记',
        23 => '金宝博',
        14 => '韦德',
        9  => '威廉',
        22 => '10Bet',
        33 => '永利高',
        35 => '盛和',
        19 => 'interW',
        18 => 'Eurobet',
        7  => 'SNAI',
        42 => '18Bet',
        45 => 'ManbetX',
      ),
    //aob_odds company_id
    'AOB_COMPANY_ID' => array (
        3  => 'ＳＢ',
        8  => 'Bet365',
        17 => '明陞',
        23 => '金宝博',
        24 => '沙巴',
        31 => '利记',
        1  => '澳彩',
        12 => '易胜博',
        4  => '立博',
        7  => 'SNAI',
        9 => '威廉希尔',
        19 => 'Interwetten',
        22 => '10Bet',
        14 => '韦德',
        35 => '盈禾',
        42 => '18Bet',
        45 => 'ManbetX',
      ),
    //赔率公司ID-名称,篮球
    'DB_BK_COMPANY_ODDS' =>array (
        1 => '澳门',
        2 => '易胜博',
        3 => '皇冠',
        8 => 'Bet365',
        9 => '韦德',
    ),
     //欧赔公司统计公司
    'DB_FB_EUR_COMPANY' =>array (
        16 => '10BET',
        18 => '12BET',
        545 => 'SB',
        281 => 'bet 365',
        177 => 'Pinnacle',
        110 => 'SNAI',
        1183 => 'ManbetX',
        60 => 'STS',
        976 => '18Bet',
        450 => 'TOTO',
        173 => 'bet-at-home',
        80 => '澳门',
        255 => 'Bwin',
        422 => '博天堂',
        88 => 'Coral',
        499 => '金宝博',
        82 => '立博',
        71 => 'Eurobet',
        70 => 'Expekt',
        474 => '利记sbobet',
        104 => 'Interwetten',
        517 => '明陞',
        97 => 'Nike',
        115 => '威廉希尔',
        4 => 'Nordicbet',
        81 => '伟德',
        649 => 'IBCBET',
        90 => '易胜博',
        158 => 'Gamebookers',
        659 => '盈禾',
    ),
    //篮球欧赔公司统计公司
    'DB_BK_EUR_COMPANY' =>array (
        16 => 'Stan James',
        17 => 'Pinnacle Sports',
        26 => 'William Hill',
        43 => 'Coral',
        77 => 'Expekt',
        82 => 'Vcbet',
        518 => 'Bet365',
        265 => 'Macauslot',
        272 => 'BWin',
        317 => 'SNAI',
        458 => 'SB',
        431 => 'Sporttery ',
        3 => 'Interwetten',
        4 => 'Admiral',
        6 => 'Easybets ',
    ),
    'BF_COMPANY_ODDS' =>array (
        3  => 'SB',
        1  => '澳彩',
        8  => 'Bet365',
        12 => '易胜博',
        14 => '韦德',
        17 => '明陞',
        22 => '10Bet',
        23 => '金宝博',
        24 => '沙巴',
        31 => '利记',
        35 => '盈禾',
        42 => '18Bet',
        45 => 'ManbetX',
        4  => '立博',
        19 => 'Interwetten'
    ),
    'alikeHistoryCompany' => array(
        'companyId'   => 8,
        'companyName' => 'bet365',
    ),
  );
?>