<?php
/**
 *会员管理的渠道查询中的渠道名配置
 *@author liangzk <1343724998@qq.com>
 *@since  2016-06-16 v1.0
 */
return [
    'channel_code'=>[
        'f1'=>'小米商店',
        'f2'=>'360助手',
        'f3'=>'百度手机助手',
        'f4'=>'91助手',
        'f5'=>'安卓市场',
        'f6'=>'豌豆荚',
        'f7'=>'应用宝',
        'f8'=>'安智市场',
        'f9'=>'联想开发平台',
        'f10'=>'OPPO开发社区',
        'f11'=>'华为应用市场',
        'f12'=>'应用汇',
        'f13'=>'机锋市场',
        'f14'=>'搜狗手机助手',
        'f15'=>'PP助手（淘宝手机助手、UC应用商店）',
        'f16'=>'魅族开发者',
        'f17'=>'3G门户',
        'f18'=>'木蚂蚁',
        'f19'=>'历趣市场',
        'f20'=>'优亿市场',
        'f21'=>'金立开发者平台',
        'f22'=>'三星应用商店',
        'f23'=>'酷传（其它）',
        'f24'=>'乐视应用商店',
        'f25'=>'锤子手机',
        'f26'=>'VIVO手机',
        'f27'=>'联通沃商店',
        'f28'=>'N多市场',
        'f29'=>'中国电信天翼开发平台',
        'f30'=>'中国移动开发社区',
        'f31'=>'天翼空间',
        'f32'=>'博应用',
        'f33'=>'白云联边公园',
        'official'     =>'官网',
        'fox008'=>'猎球者',
        'm'  =>'M站',
        'm2' =>'M2站',
        'web' =>'web网站',
        'company'      =>'绿色公司版',
        'zuzu'         =>'族族(找场包)',
        'basketball'   =>'JRS篮球比分',
        'personal'     =>'比分直播版(浩南包)',
        'worldCup'     =>'世界杯(炯波包)',
        'valuableBook' =>'比分直播宝典',
        'topSpeed'     =>'极速比分',
        'scoreApp'     =>'纯比分版',
        'newsApp'      =>'纯资讯版',
        'master'       =>'分析大师',
        'enterprise'   =>'绿色企业版',
    ],
    //来源网站：http://theiphonewiki.com/wiki/Models
    'iphone_wiki' => [
        'iPhone1,1' => 'iPhone',
        'iPhone1,2' => 'iPhone 3G',
        'iPhone2,1' => 'iPhone 3GS',
        'iPhone3,1' => 'iPhone 4',
        'iPhone3,2' => 'iPhone 4',
        'iPhone3,3' => 'iPhone 4',
        'iPhone4,1' => 'iPhone 4s',
        'iPhone5,1' => 'iPhone 5',
        'iPhone5,2' => 'iPhone 5',
        'iPhone5,3' => 'iPhone 5c',
        'iPhone5,4' => 'iPhone 5c',
        'iPhone6,1' => 'iPhone 5s',
        'iPhone6,2' => 'iPhone 5s',
        'iPhone7,2' => 'iPhone 6',
        'iPhone7,1' => 'iPhone 6 Plus',
        'iPhone8,1' => 'iPhone 6s',
        'iPhone8,2' => 'iPhone 6s Plus',
        'iPhone8,4' => 'iPhone SE',
        'iPhone9,1' => 'iPhone 7',
        'iPhone9,3' => 'iPhone 7',
        'iPhone9,2' => 'iPhone 7 Plus',
        'iPhone9,4' => 'iPhone 7 Plus',
        'iPhone10,1' => 'iPhone 8',
        'iPhone10,4' => 'iPhone 8',
        'iPhone10,2' => 'iPhone 8 Plus',
        'iPhone10,5' => 'iPhone 8 Plus',
        'iPhone10,3' => 'iPhone X',
        'iPhone10,6' => 'iPhone X',
    ],
];


?>
